/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CryptoSymbol = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AlertSettings = IDL.Record({
  'enabled' : IDL.Bool,
  'thresholdPercent' : IDL.Float64,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'lastActive' : Time,
});
export const ForecastMethod = IDL.Variant({
  'movingAverage' : IDL.Null,
  'exponentialSmoothing' : IDL.Null,
  'linearRegression' : IDL.Null,
});
export const LiveMarketResponse = IDL.Record({
  'change24h' : IDL.Float64,
  'marketCap' : IDL.Float64,
  'price' : IDL.Float64,
});
export const DisplaySymbol = IDL.Text;
export const SymbolPair = IDL.Record({
  'network' : CryptoSymbol,
  'display' : DisplaySymbol,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCryptoToWatchlist' : IDL.Func([CryptoSymbol], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'debugCheckSymbol' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'debugFetchRawTicker' : IDL.Func([], [IDL.Text], []),
  'debugGetAdminList' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'debugParseTicker' : IDL.Func([IDL.Text], [IDL.Text], []),
  'debugResetSystem' : IDL.Func([], [IDL.Text], ['query']),
  'debugSymbolCount' : IDL.Func([], [IDL.Nat], ['query']),
  'debugTestCoinGecko' : IDL.Func([], [IDL.Text], []),
  'debugValidSymbols' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'fetchCoinGeckoData' : IDL.Func([CryptoSymbol], [IDL.Opt(IDL.Text)], []),
  'getAlertSettings' : IDL.Func(
      [CryptoSymbol],
      [IDL.Opt(AlertSettings)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getForecastMethod' : IDL.Func(
      [CryptoSymbol],
      [IDL.Opt(ForecastMethod)],
      ['query'],
    ),
  'getLiveMarketData' : IDL.Func(
      [CryptoSymbol],
      [IDL.Opt(LiveMarketResponse)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getValidSymbols' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(DisplaySymbol, SymbolPair))],
      ['query'],
    ),
  'getWatchlist' : IDL.Func([], [IDL.Vec(CryptoSymbol)], ['query']),
  'initializeCryptoSystem' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loadValidCryptoSymbols' : IDL.Func([], [], []),
  'removeCryptoFromWatchlist' : IDL.Func([CryptoSymbol], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAlertSettings' : IDL.Func([CryptoSymbol, AlertSettings], [], []),
  'setForecastMethod' : IDL.Func([CryptoSymbol, ForecastMethod], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CryptoSymbol = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AlertSettings = IDL.Record({
    'enabled' : IDL.Bool,
    'thresholdPercent' : IDL.Float64,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'lastActive' : Time });
  const ForecastMethod = IDL.Variant({
    'movingAverage' : IDL.Null,
    'exponentialSmoothing' : IDL.Null,
    'linearRegression' : IDL.Null,
  });
  const LiveMarketResponse = IDL.Record({
    'change24h' : IDL.Float64,
    'marketCap' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const DisplaySymbol = IDL.Text;
  const SymbolPair = IDL.Record({
    'network' : CryptoSymbol,
    'display' : DisplaySymbol,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCryptoToWatchlist' : IDL.Func([CryptoSymbol], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'debugCheckSymbol' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'debugFetchRawTicker' : IDL.Func([], [IDL.Text], []),
    'debugGetAdminList' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'debugParseTicker' : IDL.Func([IDL.Text], [IDL.Text], []),
    'debugResetSystem' : IDL.Func([], [IDL.Text], ['query']),
    'debugSymbolCount' : IDL.Func([], [IDL.Nat], ['query']),
    'debugTestCoinGecko' : IDL.Func([], [IDL.Text], []),
    'debugValidSymbols' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'fetchCoinGeckoData' : IDL.Func([CryptoSymbol], [IDL.Opt(IDL.Text)], []),
    'getAlertSettings' : IDL.Func(
        [CryptoSymbol],
        [IDL.Opt(AlertSettings)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getForecastMethod' : IDL.Func(
        [CryptoSymbol],
        [IDL.Opt(ForecastMethod)],
        ['query'],
      ),
    'getLiveMarketData' : IDL.Func(
        [CryptoSymbol],
        [IDL.Opt(LiveMarketResponse)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getValidSymbols' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(DisplaySymbol, SymbolPair))],
        ['query'],
      ),
    'getWatchlist' : IDL.Func([], [IDL.Vec(CryptoSymbol)], ['query']),
    'initializeCryptoSystem' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loadValidCryptoSymbols' : IDL.Func([], [], []),
    'removeCryptoFromWatchlist' : IDL.Func([CryptoSymbol], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAlertSettings' : IDL.Func([CryptoSymbol, AlertSettings], [], []),
    'setForecastMethod' : IDL.Func([CryptoSymbol, ForecastMethod], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };