/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CryptoSymbol = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AlertDirection = IDL.Variant({
  'above' : IDL.Null,
  'below' : IDL.Null,
});
export const AlertInput = IDL.Record({
  'direction' : AlertDirection,
  'targetPrice' : IDL.Float64,
  'symbol' : CryptoSymbol,
});
export const DisplaySymbol = IDL.Text;
export const LiveMarketResponse = IDL.Record({
  'change24h' : IDL.Float64,
  'marketCap' : IDL.Float64,
  'price' : IDL.Float64,
});
export const Time = IDL.Int;
export const PriceAlert = IDL.Record({
  'alertType' : IDL.Text,
  'direction' : AlertDirection,
  'createdAt' : Time,
  'targetPrice' : IDL.Float64,
  'isActive' : IDL.Bool,
  'symbol' : CryptoSymbol,
});
export const AlertSettings = IDL.Record({
  'enabled' : IDL.Bool,
  'thresholdPercent' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'lastActive' : Time,
});
export const CommandCategory = IDL.Variant({
  'admin' : IDL.Null,
  'data' : IDL.Null,
  'test' : IDL.Null,
  'user' : IDL.Null,
});
export const CommandEntry = IDL.Record({
  'description' : IDL.Text,
  'command' : IDL.Text,
  'category' : CommandCategory,
});
export const ForecastMethod = IDL.Variant({
  'movingAverage' : IDL.Null,
  'exponentialSmoothing' : IDL.Null,
  'linearRegression' : IDL.Null,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SymbolPair = IDL.Record({
  'network' : CryptoSymbol,
  'display' : DisplaySymbol,
});
export const InitializePermanentAdminResult = IDL.Record({
  'verifiedCaller' : IDL.Principal,
  'permanentAdminSet' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCryptoToWatchlist' : IDL.Func([CryptoSymbol], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkAndInitializeUser' : IDL.Func([], [IDL.Bool], []),
  'createOrUpdatePriceAlert' : IDL.Func([AlertInput], [], []),
  'debugCheckSymbol' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'debugGetAdminList' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'debugSymbolCount' : IDL.Func([], [IDL.Nat], ['query']),
  'debugValidSymbols' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(DisplaySymbol, CryptoSymbol))],
      ['query'],
    ),
  'deleteAlert' : IDL.Func([IDL.Nat], [], []),
  'disableAlert' : IDL.Func([IDL.Nat], [], []),
  'disableAllAlerts' : IDL.Func([], [], []),
  'emergencyGrantAdmin' : IDL.Func([IDL.Principal], [], []),
  'fetchCoinGeckoData' : IDL.Func(
      [CryptoSymbol],
      [IDL.Opt(LiveMarketResponse)],
      [],
    ),
  'getActiveAlerts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, PriceAlert))],
      ['query'],
    ),
  'getAdminInitializationErrorMessage' : IDL.Func(
      [],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getAdminList' : IDL.Func([], [IDL.Vec(IDL.Principal)], []),
  'getAlertSettings' : IDL.Func(
      [CryptoSymbol],
      [IDL.Opt(AlertSettings)],
      ['query'],
    ),
  'getAlerts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, PriceAlert))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommandRegistry' : IDL.Func([], [IDL.Vec(CommandEntry)], ['query']),
  'getForecastMethod' : IDL.Func(
      [CryptoSymbol],
      [IDL.Opt(ForecastMethod)],
      ['query'],
    ),
  'getLiveMarketData' : IDL.Func(
      [CryptoSymbol],
      [IDL.Opt(LiveMarketResponse)],
      [],
    ),
  'getRole' : IDL.Func([], [Role], []),
  'getSingleAlert' : IDL.Func([IDL.Nat], [IDL.Opt(PriceAlert)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getValidSymbols' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(DisplaySymbol, SymbolPair))],
      ['query'],
    ),
  'getWatchlist' : IDL.Func([], [IDL.Vec(CryptoSymbol)], ['query']),
  'grantUserPermission' : IDL.Func([IDL.Principal], [], []),
  'initializePermanentAdmin' : IDL.Func(
      [],
      [InitializePermanentAdminResult],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loadValidCryptoSymbols' : IDL.Func([], [], []),
  'registerSelfAsUser' : IDL.Func([], [], []),
  'registerWithRole' : IDL.Func([Role], [], []),
  'removeCryptoFromWatchlist' : IDL.Func([CryptoSymbol], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePermanentAdmin' : IDL.Func([IDL.Principal], [], []),
  'setAlertSettings' : IDL.Func([CryptoSymbol, AlertSettings], [], []),
  'setForecastMethod' : IDL.Func([CryptoSymbol, ForecastMethod], [], []),
  'testAPIResponseFormat' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'testAlertSettings' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Bool], []),
  'testAllNineSymbols' : IDL.Func([], [IDL.Bool], []),
  'testBulkSymbolValidation' : IDL.Func([], [IDL.Bool], []),
  'testForecastMethod' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'testHistoricalDataFetch' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'testSymbolDataIntegrity' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'testWatchlistAdd' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'testWatchlistRemove' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CryptoSymbol = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AlertDirection = IDL.Variant({
    'above' : IDL.Null,
    'below' : IDL.Null,
  });
  const AlertInput = IDL.Record({
    'direction' : AlertDirection,
    'targetPrice' : IDL.Float64,
    'symbol' : CryptoSymbol,
  });
  const DisplaySymbol = IDL.Text;
  const LiveMarketResponse = IDL.Record({
    'change24h' : IDL.Float64,
    'marketCap' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const Time = IDL.Int;
  const PriceAlert = IDL.Record({
    'alertType' : IDL.Text,
    'direction' : AlertDirection,
    'createdAt' : Time,
    'targetPrice' : IDL.Float64,
    'isActive' : IDL.Bool,
    'symbol' : CryptoSymbol,
  });
  const AlertSettings = IDL.Record({
    'enabled' : IDL.Bool,
    'thresholdPercent' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'lastActive' : Time });
  const CommandCategory = IDL.Variant({
    'admin' : IDL.Null,
    'data' : IDL.Null,
    'test' : IDL.Null,
    'user' : IDL.Null,
  });
  const CommandEntry = IDL.Record({
    'description' : IDL.Text,
    'command' : IDL.Text,
    'category' : CommandCategory,
  });
  const ForecastMethod = IDL.Variant({
    'movingAverage' : IDL.Null,
    'exponentialSmoothing' : IDL.Null,
    'linearRegression' : IDL.Null,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SymbolPair = IDL.Record({
    'network' : CryptoSymbol,
    'display' : DisplaySymbol,
  });
  const InitializePermanentAdminResult = IDL.Record({
    'verifiedCaller' : IDL.Principal,
    'permanentAdminSet' : IDL.Bool,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCryptoToWatchlist' : IDL.Func([CryptoSymbol], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkAndInitializeUser' : IDL.Func([], [IDL.Bool], []),
    'createOrUpdatePriceAlert' : IDL.Func([AlertInput], [], []),
    'debugCheckSymbol' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'debugGetAdminList' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'debugSymbolCount' : IDL.Func([], [IDL.Nat], ['query']),
    'debugValidSymbols' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(DisplaySymbol, CryptoSymbol))],
        ['query'],
      ),
    'deleteAlert' : IDL.Func([IDL.Nat], [], []),
    'disableAlert' : IDL.Func([IDL.Nat], [], []),
    'disableAllAlerts' : IDL.Func([], [], []),
    'emergencyGrantAdmin' : IDL.Func([IDL.Principal], [], []),
    'fetchCoinGeckoData' : IDL.Func(
        [CryptoSymbol],
        [IDL.Opt(LiveMarketResponse)],
        [],
      ),
    'getActiveAlerts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, PriceAlert))],
        ['query'],
      ),
    'getAdminInitializationErrorMessage' : IDL.Func(
        [],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getAdminList' : IDL.Func([], [IDL.Vec(IDL.Principal)], []),
    'getAlertSettings' : IDL.Func(
        [CryptoSymbol],
        [IDL.Opt(AlertSettings)],
        ['query'],
      ),
    'getAlerts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, PriceAlert))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommandRegistry' : IDL.Func([], [IDL.Vec(CommandEntry)], ['query']),
    'getForecastMethod' : IDL.Func(
        [CryptoSymbol],
        [IDL.Opt(ForecastMethod)],
        ['query'],
      ),
    'getLiveMarketData' : IDL.Func(
        [CryptoSymbol],
        [IDL.Opt(LiveMarketResponse)],
        [],
      ),
    'getRole' : IDL.Func([], [Role], []),
    'getSingleAlert' : IDL.Func([IDL.Nat], [IDL.Opt(PriceAlert)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getValidSymbols' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(DisplaySymbol, SymbolPair))],
        ['query'],
      ),
    'getWatchlist' : IDL.Func([], [IDL.Vec(CryptoSymbol)], ['query']),
    'grantUserPermission' : IDL.Func([IDL.Principal], [], []),
    'initializePermanentAdmin' : IDL.Func(
        [],
        [InitializePermanentAdminResult],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loadValidCryptoSymbols' : IDL.Func([], [], []),
    'registerSelfAsUser' : IDL.Func([], [], []),
    'registerWithRole' : IDL.Func([Role], [], []),
    'removeCryptoFromWatchlist' : IDL.Func([CryptoSymbol], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePermanentAdmin' : IDL.Func([IDL.Principal], [], []),
    'setAlertSettings' : IDL.Func([CryptoSymbol, AlertSettings], [], []),
    'setForecastMethod' : IDL.Func([CryptoSymbol, ForecastMethod], [], []),
    'testAPIResponseFormat' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'testAlertSettings' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Bool], []),
    'testAllNineSymbols' : IDL.Func([], [IDL.Bool], []),
    'testBulkSymbolValidation' : IDL.Func([], [IDL.Bool], []),
    'testForecastMethod' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'testHistoricalDataFetch' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'testSymbolDataIntegrity' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'testWatchlistAdd' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'testWatchlistRemove' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };