/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlertSettings {
  'enabled' : boolean,
  'thresholdPercent' : number,
}
export type CryptoSymbol = string;
export type DisplaySymbol = string;
export type ForecastMethod = { 'movingAverage' : null } |
  { 'exponentialSmoothing' : null } |
  { 'linearRegression' : null };
export interface LiveMarketResponse {
  'change24h' : number,
  'marketCap' : number,
  'price' : number,
}
export interface SymbolPair {
  'network' : CryptoSymbol,
  'display' : DisplaySymbol,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'lastActive' : Time }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCryptoToWatchlist' : ActorMethod<[CryptoSymbol], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'debugCheckSymbol' : ActorMethod<[string], string>,
  'debugFetchRawTicker' : ActorMethod<[], string>,
  'debugGetAdminList' : ActorMethod<[], Array<Principal>>,
  'debugParseTicker' : ActorMethod<[string], string>,
  'debugResetSystem' : ActorMethod<[], string>,
  'debugSymbolCount' : ActorMethod<[], bigint>,
  'debugTestCoinGecko' : ActorMethod<[], string>,
  'debugValidSymbols' : ActorMethod<[], Array<[string, string]>>,
  'fetchCoinGeckoData' : ActorMethod<[CryptoSymbol], [] | [string]>,
  'getAlertSettings' : ActorMethod<[CryptoSymbol], [] | [AlertSettings]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getForecastMethod' : ActorMethod<[CryptoSymbol], [] | [ForecastMethod]>,
  'getLiveMarketData' : ActorMethod<[CryptoSymbol], [] | [LiveMarketResponse]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getValidSymbols' : ActorMethod<[], Array<[DisplaySymbol, SymbolPair]>>,
  'getWatchlist' : ActorMethod<[], Array<CryptoSymbol>>,
  'initializeCryptoSystem' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loadValidCryptoSymbols' : ActorMethod<[], undefined>,
  'removeCryptoFromWatchlist' : ActorMethod<[CryptoSymbol], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAlertSettings' : ActorMethod<[CryptoSymbol, AlertSettings], undefined>,
  'setForecastMethod' : ActorMethod<[CryptoSymbol, ForecastMethod], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];