/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AlertDirection = { 'above' : null } |
  { 'below' : null };
export interface AlertInput {
  'direction' : AlertDirection,
  'targetPrice' : number,
  'symbol' : CryptoSymbol,
}
export interface AlertSettings {
  'enabled' : boolean,
  'thresholdPercent' : number,
}
export type CommandCategory = { 'admin' : null } |
  { 'data' : null } |
  { 'test' : null } |
  { 'user' : null };
export interface CommandEntry {
  'description' : string,
  'command' : string,
  'category' : CommandCategory,
}
export type CryptoSymbol = string;
export type DisplaySymbol = string;
export type ForecastMethod = { 'movingAverage' : null } |
  { 'exponentialSmoothing' : null } |
  { 'linearRegression' : null };
export interface InitializePermanentAdminResult {
  'verifiedCaller' : Principal,
  'permanentAdminSet' : boolean,
}
export interface LiveMarketResponse {
  'change24h' : number,
  'marketCap' : number,
  'price' : number,
}
export interface PriceAlert {
  'alertType' : string,
  'direction' : AlertDirection,
  'createdAt' : Time,
  'targetPrice' : number,
  'isActive' : boolean,
  'symbol' : CryptoSymbol,
}
export type Role = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface SymbolPair {
  'network' : CryptoSymbol,
  'display' : DisplaySymbol,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'lastActive' : Time }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCryptoToWatchlist' : ActorMethod<[CryptoSymbol], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAndInitializeUser' : ActorMethod<[], boolean>,
  'createOrUpdatePriceAlert' : ActorMethod<[AlertInput], undefined>,
  'debugCheckSymbol' : ActorMethod<[string], boolean>,
  'debugGetAdminList' : ActorMethod<[], Array<Principal>>,
  'debugSymbolCount' : ActorMethod<[], bigint>,
  'debugValidSymbols' : ActorMethod<[], Array<[DisplaySymbol, CryptoSymbol]>>,
  'deleteAlert' : ActorMethod<[bigint], undefined>,
  'disableAlert' : ActorMethod<[bigint], undefined>,
  'disableAllAlerts' : ActorMethod<[], undefined>,
  'emergencyGrantAdmin' : ActorMethod<[Principal], undefined>,
  'fetchCoinGeckoData' : ActorMethod<[CryptoSymbol], [] | [LiveMarketResponse]>,
  'getActiveAlerts' : ActorMethod<[], Array<[bigint, PriceAlert]>>,
  'getAdminInitializationErrorMessage' : ActorMethod<[], [] | [string]>,
  'getAdminList' : ActorMethod<[], Array<Principal>>,
  'getAlertSettings' : ActorMethod<[CryptoSymbol], [] | [AlertSettings]>,
  'getAlerts' : ActorMethod<[], Array<[bigint, PriceAlert]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommandRegistry' : ActorMethod<[], Array<CommandEntry>>,
  'getForecastMethod' : ActorMethod<[CryptoSymbol], [] | [ForecastMethod]>,
  'getLiveMarketData' : ActorMethod<[CryptoSymbol], [] | [LiveMarketResponse]>,
  'getRole' : ActorMethod<[], Role>,
  'getSingleAlert' : ActorMethod<[bigint], [] | [PriceAlert]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getValidSymbols' : ActorMethod<[], Array<[DisplaySymbol, SymbolPair]>>,
  'getWatchlist' : ActorMethod<[], Array<CryptoSymbol>>,
  'grantUserPermission' : ActorMethod<[Principal], undefined>,
  'initializePermanentAdmin' : ActorMethod<[], InitializePermanentAdminResult>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loadValidCryptoSymbols' : ActorMethod<[], undefined>,
  'registerSelfAsUser' : ActorMethod<[], undefined>,
  'registerWithRole' : ActorMethod<[Role], undefined>,
  'removeCryptoFromWatchlist' : ActorMethod<[CryptoSymbol], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePermanentAdmin' : ActorMethod<[Principal], undefined>,
  'setAlertSettings' : ActorMethod<[CryptoSymbol, AlertSettings], undefined>,
  'setForecastMethod' : ActorMethod<[CryptoSymbol, ForecastMethod], undefined>,
  'testAPIResponseFormat' : ActorMethod<[string], boolean>,
  'testAlertSettings' : ActorMethod<[string, number], boolean>,
  'testAllNineSymbols' : ActorMethod<[], boolean>,
  'testBulkSymbolValidation' : ActorMethod<[], boolean>,
  'testForecastMethod' : ActorMethod<[string, string], boolean>,
  'testHistoricalDataFetch' : ActorMethod<[string], boolean>,
  'testSymbolDataIntegrity' : ActorMethod<[string], boolean>,
  'testWatchlistAdd' : ActorMethod<[string], boolean>,
  'testWatchlistRemove' : ActorMethod<[string], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];