/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface SymbolPair {
    network: CryptoSymbol;
    display: DisplaySymbol;
}
export interface LiveMarketResponse {
    change24h: number;
    marketCap: number;
    price: number;
}
export type DisplaySymbol = string;
export type CryptoSymbol = string;
export interface AlertSettings {
    enabled: boolean;
    thresholdPercent: number;
}
export interface UserProfile {
    name: string;
    lastActive: Time;
}
export interface http_header {
    value: string;
    name: string;
}
export enum ForecastMethod {
    movingAverage = "movingAverage",
    exponentialSmoothing = "exponentialSmoothing",
    linearRegression = "linearRegression"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCryptoToWatchlist(symbol: CryptoSymbol): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    debugCheckSymbol(symbol: string): Promise<string>;
    debugFetchRawTicker(): Promise<string>;
    debugGetAdminList(): Promise<Array<Principal>>;
    debugParseTicker(symbol: string): Promise<string>;
    debugResetSystem(): Promise<string>;
    debugSymbolCount(): Promise<bigint>;
    debugTestCoinGecko(): Promise<string>;
    debugValidSymbols(): Promise<Array<[string, string]>>;
    fetchCoinGeckoData(symbol: CryptoSymbol): Promise<string | null>;
    getAlertSettings(symbol: CryptoSymbol): Promise<AlertSettings | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getForecastMethod(symbol: CryptoSymbol): Promise<ForecastMethod | null>;
    getLiveMarketData(symbol: CryptoSymbol): Promise<LiveMarketResponse | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getValidSymbols(): Promise<Array<[DisplaySymbol, SymbolPair]>>;
    getWatchlist(): Promise<Array<CryptoSymbol>>;
    initializeCryptoSystem(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    loadValidCryptoSymbols(): Promise<void>;
    removeCryptoFromWatchlist(symbol: CryptoSymbol): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setAlertSettings(symbol: CryptoSymbol, settings: AlertSettings): Promise<void>;
    setForecastMethod(symbol: CryptoSymbol, method: ForecastMethod): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AlertSettings as _AlertSettings, ForecastMethod as _ForecastMethod, LiveMarketResponse as _LiveMarketResponse, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCryptoToWatchlist(arg0: CryptoSymbol): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCryptoToWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCryptoToWatchlist(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async debugCheckSymbol(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.debugCheckSymbol(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.debugCheckSymbol(arg0);
            return result;
        }
    }
    async debugFetchRawTicker(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.debugFetchRawTicker();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.debugFetchRawTicker();
            return result;
        }
    }
    async debugGetAdminList(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.debugGetAdminList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.debugGetAdminList();
            return result;
        }
    }
    async debugParseTicker(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.debugParseTicker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.debugParseTicker(arg0);
            return result;
        }
    }
    async debugResetSystem(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.debugResetSystem();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.debugResetSystem();
            return result;
        }
    }
    async debugSymbolCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.debugSymbolCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.debugSymbolCount();
            return result;
        }
    }
    async debugTestCoinGecko(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.debugTestCoinGecko();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.debugTestCoinGecko();
            return result;
        }
    }
    async debugValidSymbols(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.debugValidSymbols();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.debugValidSymbols();
            return result;
        }
    }
    async fetchCoinGeckoData(arg0: CryptoSymbol): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchCoinGeckoData(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchCoinGeckoData(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlertSettings(arg0: CryptoSymbol): Promise<AlertSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertSettings(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertSettings(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getForecastMethod(arg0: CryptoSymbol): Promise<ForecastMethod | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getForecastMethod(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForecastMethod(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLiveMarketData(arg0: CryptoSymbol): Promise<LiveMarketResponse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveMarketData(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveMarketData(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getValidSymbols(): Promise<Array<[DisplaySymbol, SymbolPair]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getValidSymbols();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getValidSymbols();
            return result;
        }
    }
    async getWatchlist(): Promise<Array<CryptoSymbol>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlist();
            return result;
        }
    }
    async initializeCryptoSystem(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeCryptoSystem();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeCryptoSystem();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loadValidCryptoSymbols(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.loadValidCryptoSymbols();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loadValidCryptoSymbols();
            return result;
        }
    }
    async removeCryptoFromWatchlist(arg0: CryptoSymbol): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCryptoFromWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCryptoFromWatchlist(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAlertSettings(arg0: CryptoSymbol, arg1: AlertSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAlertSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAlertSettings(arg0, arg1);
            return result;
        }
    }
    async setForecastMethod(arg0: CryptoSymbol, arg1: ForecastMethod): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setForecastMethod(arg0, to_candid_ForecastMethod_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setForecastMethod(arg0, to_candid_ForecastMethod_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_ForecastMethod_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ForecastMethod): ForecastMethod {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LiveMarketResponse]): LiveMarketResponse | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AlertSettings]): AlertSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ForecastMethod]): ForecastMethod | null {
    return value.length === 0 ? null : from_candid_ForecastMethod_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    movingAverage: null;
} | {
    exponentialSmoothing: null;
} | {
    linearRegression: null;
}): ForecastMethod {
    return "movingAverage" in value ? ForecastMethod.movingAverage : "exponentialSmoothing" in value ? ForecastMethod.exponentialSmoothing : "linearRegression" in value ? ForecastMethod.linearRegression : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_ForecastMethod_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ForecastMethod): _ForecastMethod {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ForecastMethod): {
    movingAverage: null;
} | {
    exponentialSmoothing: null;
} | {
    linearRegression: null;
} {
    return value == ForecastMethod.movingAverage ? {
        movingAverage: null
    } : value == ForecastMethod.exponentialSmoothing ? {
        exponentialSmoothing: null
    } : value == ForecastMethod.linearRegression ? {
        linearRegression: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
